### ISSUE TITLE
repo_path should default to CIRCLE_WORKING_DIRECTORY

### ISSUE THREAD

**Issue by joekohlsdorf** [mavenlink/orbs#9]
So that this can be a drop-in replacement for CircleCIs `checkout` command, the default check out path should be equal to what CircleCI provides.

**Comment by juanca** [comment]
Appreciate the feedback.

Let me push those changes and test against our internal repositories.

**Comment by juanca** [comment]
This has been released in 1.2.0, better documentation in 1.2.1
